### ISSUE TITLE
Step 4 Error

### ISSUE THREAD

**Issue by amilopowers** [YBJazzer/GEBADR#1]
Hello

After running the first script I get the following error: 
```

[amilopowers@polarbaer ~]$ python3 '/home/amilopowers/Dokumente/OSM-GEBADR/GEBADR-master/GEBADR_OSMimport_script1_converts_GEBADR_to_OSMstyle.py' 
Traceback (most recent call last):
  File "/home/amilopowers/Dokumente/OSM-GEBADR/GEBADR-master/GEBADR_OSMimport_script1_converts_GEBADR_to_OSMstyle.py", line 75, in <module>
    ch_east  = data['GROBKOOR_E']
KeyError: 'GROBKOOR_E'

```

How can I fix that?

Gruss
amilopowers

**Comment by YBJazzer** [comment]
Hi amilopowers
I could reconstruct the error. It happens when the delimiter is incorrect. The delimiter separates the column entries.

In the script, I use semicolon ";" as delimiter. When you create a .csv in the German Version of Microsoft Excel, it automatically saves with ";" as delimiter. That's the way I did. But if you use an English Version or another spreadsheet like Appache Open Office Calc, I think the delimiter is comma ",".

To correct that do the following:
First, open your GEBADR_GADR.csv file in a text editor and check if the entries are separated by semicolon or by comma.
If entries are separated by comma, then this is for sure the problem. 

To fix the problem, open the script in a text editor. 
Now change in line 57 the delimiter from ";" to your delimiter, probably ",".
Then it should work.

Grüsse zurück
YBJazzer

**Comment by amilopowers** [comment]
So that doesn't change anything. I still get that message:
```

[amilopowers@polarbaer ~]$ python3 '/home/amilopowers/Dokumente/OSM-GEBADR/GEBADR-master/GEBADR_OSMimport_script1_converts_GEBADR_to_OSMstyle.py' 
Traceback (most recent call last):
  File "/home/amilopowers/Dokumente/OSM-GEBADR/GEBADR-master/GEBADR_OSMimport_script1_converts_GEBADR_to_OSMstyle.py", line 75, in <module>
    ch_east  = data['GROBKOOR_E']
KeyError: 'GROBKOOR_E'
```
When opening the .dbf file I can choose from a number of different character sets in LibreOffice 5.2.3.3
![character set](https://cloud.githubusercontent.com/assets/9914682/21015039/aa8b5dde-bd60-11e6-9c53-7df22d4d1d18.png)

Because I don't know which is equal to that MS-DOS you say in you guide I took UTF-8.
When saving to .csv I used the same UTF-8 and there it is: delimiters "," (apparently). 
![save](https://cloud.githubusercontent.com/assets/9914682/21015309/cf61843e-bd61-11e6-8204-56c5447a822e.png)


I could change delimiter but since I already adapted the script that shouldn't make any problems any more.

I use Python 3.5.2.

For reference I attached the GEBARD_GADR.csv file and the script.
[GEBADR.zip](https://github.com/YBJazzer/GEBADR/files/639795/GEBADR.zip)

**Comment by YBJazzer** [comment]
Hi amilopowers,
thanks for sharing the .csv. I see the problem. I tested your files from the .zip folder and by a quick minor change made it succesfully running.

A short explanation first: the .dbf file (which is a special file for databases) makes a difference between the style of the header line and all other lines (database entries). Therefore, you will see a difference in LibreOffice between headers and entries (and now I remember I saw it in Open Office Calc as well). A header looks like this:
"LOKALISAT,C,60","GEBNR,C,12","BFSNR,N,4,0"

The C,60 and C,12 and N,4,0 are something specific for headers in the .dbf style.

In comparison, Excel knows that there's a difference between headers (the first line) and entries (all other lines) in the .dbf file style. Excel automatically recognises that these letters and numbers do not make too much sense and does not show this additional information when opening and saving, so Excel will create the following headers:
LOKALISAT;GEBNR;BFSNR

Now you see the difference. The Python script has a problem to recognise the headers. Therefore it cannot read the column data and gives the same error as for a wrong delimiter. 

From your script, I simply deleted this additional information like "C,60" and "C,12" and "N,4,0" and so on for every header. You can keep the quotation marks '"', it makes no difference. When your headers (= the first line) look like this, it should work:
"LOKALISAT","GEBNR","BFSNR" etc.

or:
LOKALISAT,GEBNR,BFSNR etc.

I think this will fix the problem. I will also update the instructions to make that clear.

Liebe Grüsse
YBJazzer

**Comment by YBJazzer** [comment]
Additional remark about the .csv (MS DOS) style.

First, in LibreOffice and OpenOffice Calc you do not have the problem described below!
So it has no connection with the fact that the script didn't run at first.

The following problem appeared to me when not saving the .csv in MS DOS style (there are other .csv styles in Excel): 
The umlauts and French letters were shown wrong. So words like Hôpital, Dörfli, Gebäude etc. were shown something like this: H??pital, D??rfli, Geb??ude. It took me quite some time and nerves to figure that out. Therefore I mention it prominently, but it's not crucial for running the script.

**Comment by amilopowers** [comment]
Thanks for your explanation. I will test it in the following days. And yes if successful I think it might make semse to update the instrutions.

**Comment by amilopowers** [comment]
Yours script worked now!

My header looks now like that:
![calc](https://cloud.githubusercontent.com/assets/9914682/21074011/6980ccc2-beee-11e6-932c-24d873e52291.png)

Thank you.
